const offers = [{
  "id": "HN_01",
  "city": "Heilbronn",
  "type": ["Tageserlebnis", "Übernachtung"],
  "people": ["Einzeln", "Zu zweit"],
  "title": "Experimenta mit Genuss",
  "intro": "Erlebe ein Genuss-Wochenende in Heilbronn mit einem Besuch im Science-Center experimenta.",
  "description": "Erlebe ein genüssliches Wochenende in Heilbronn in Verbindung mit einem spannenden Besuch in der experimenta, Deutschlands größtem Science-Center.",
  "amenities": ["Zwei Übernachtungen mit Frühstück", "3-Gang-Menü im Hotel am Anreisetag", "Degustationsmenü in der Wein Villa", "Tagesticket für die experimenta"],
  "more": "",
  "link": "https://www.heilbronn.de/tourismus/reise-und-erlebnisangebote/experimenta-mit-genuss.html?pk_campaign=themenkampagne_tmbw&pk_kwd=exp_mit_genuss",
  "price": ["Ab 239 Euro pro Person im Doppelzimmer", "Ab 339 Euro pro Person im Einzelzimmer"],
  "priceRange": ">100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514491/tmbw/HN/HN_01/HN_01_01_b1xelj.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514491/tmbw/HN/HN_01/HN_01_02_j9mu5z.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623683722/tmbw/HN/HN_01/experimenta-innen_2019_rs_KBFeb20_nndwxm.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514491/tmbw/HN/HN_01/HN_01_04_b73ncp.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623683723/tmbw/HN/HN_01/experimenta-Science-Dome-Karpernfahrt_2019_ex_tuswmv.jpg"]
}, {
  "id": "HN_02",
  "city": "Heilbronn",
  "type": ["Wein", "Übernachtung"],
  "people": ["Einzeln", "Gruppe", "Zu zweit"],
  "title": "Erlebe Heilbronn und seine Weine",
  "intro": "Lerne die älteste Weinstadt Württembergs kennen.\nUrban trifft Natur. Wein und Kultur.",
  "description": "Wein und Heilbronn – eine Symbiose.\nNirgendwo sind urbanes Treiben und Natur so nah bei einander. Weinberge bis an den Stadtrand, rund 30 Weingüter im Stadtgebiet und viele Probiermöglichkeiten mitten in der City lassen Sie die Leidenschaft erleben, mit der der Weinbau in Württembergs ältester Weinstadt betrieben wird.\nBesuchen Sie den Wein Pavillon an der Neckarbühne, lernen Sie den Wein Panorama Weg mit seinen Schaustelen kennen, buchen Sie eine der Weinwanderungen mit Verkostung zwischen den Reben oder gehen Sie im Weingut auf Tauchstation – mit dem Winzer in den Keller.",
  "amenities": ["Eine Übernachtung mit Frühstück", "4er-Weinprobe an der Bar im Restaurant Beichtstuhl", "2-Tages-Ticket Gesamtnetz Nahverkehr (HNV)"],
  "more": "",
  "link": "https://www.heilbronn.de/tourismus/reise-und-erlebnisangebote/heilbronn-und-seine-weine.html?pk_campaign=themenkampagne_tmbw&pk_kwd=heilbronn_weine",
  "price": ["Ab 65 Euro pro Person im Doppelzimmer", "Ab 85 Euro pro Person im Einzelzimmer"],
  "priceRange": "50-100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623685216/tmbw/HN/HN_02/Weinerlebnisfu%CC%88hrung-Wartberg_2017_gbk_110_w5rjnh.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514502/tmbw/HN/HN_02/HN_02_02_p207so.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514502/tmbw/HN/HN_02/HN_02_03_lsiatf.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623685217/tmbw/HN/HN_02/Weinpavillon-Neckarbu%CC%88hne_2020_rs_KBAugust21_1975_a5uicj.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514501/tmbw/HN/HN_02/HN_02_05_gsor9g.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623685217/tmbw/HN/HN_02/Weindorf-Auslese-im-Weingut_2020_jh_0799_unq9ba.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623685216/tmbw/HN/HN_02/Weinpavillon-Neckarbu%CC%88hne_2020_jh_022_naqslt.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623685217/tmbw/HN/HN_02/Weindorf-Auslese-im-Weingut_2020_jh_070_mjor5l.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514501/tmbw/HN/HN_02/HN_02_06_d3view.jpg"]
}, {
  "id": "HN_03",
  "city": "Heilbronn",
  "type": "Wein",
  "people": ["Einzeln", "Gruppe", "Zu zweit"],
  "title": "Schlenderweinprobe durch Heilbronn",
  "intro": "Die etwas andere Weinprobe in der City.\nGeschichte. Geselligkeit. Genießen.",
  "description": "Die etwas andere Weinprobe in der City.\nSie schlendern durch die Heilbronner Innenstadt, halten an ausgewählten Hotspots, probieren Heilbronner Weine und lassen sich mit Ihrem Glas in der Hand durch die Stadtgeschichte führen.\nKlingt gut?\nDann schlendern Sie mit uns durch die City",
  "amenities": ["4 Proben Heilbronner Wein", "Dauer ca. 2,5 Std.", "Maximal 20 Personen"],
  "more": "",
  "link": "https://www.heilbronn.de/tourismus/stadtfuehrungen/wein-und-kulinarik/schlenderweinprobe-durch-die-heilbronner-innenstadt.html?pk_campaign=themenkampagne_tmbw&pk_kwd=schlenderweinprobe",
  "price": "25 Euro pro Person\n",
  "priceRange": "10-50€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514511/tmbw/HN/HN_03/HN_03_01_w1svzm.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514511/tmbw/HN/HN_03/HN_03_02_hrbpbp.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514512/tmbw/HN/HN_03/HN_03_03_pftyfn.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623684191/tmbw/HN/HN_03/Hafenmarktpassage_-Shopping_2019_fm_2056_mmdp3e.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514511/tmbw/HN/HN_03/HN_03_05_hom1vn.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514511/tmbw/HN/HN_03/HN_03_06_lawmvt.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623684192/tmbw/HN/HN_03/Neckarmeile-Gastronomie-Wein_2019_fm_3128_b0yufw.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514512/tmbw/HN/HN_03/HN_03_07_oii0vb.jpg"]
}, {
  "id": "HN_04",
  "city": "Heilbronn",
  "type": "Stadtführung",
  "people": ["Einzeln", "Familie", "Zu zweit", "Gruppe"],
  "title": "Kanu-Stadtrundfahrten auf dem Neckar",
  "intro": "Erlebe und entdecke Heilbronn auf ganz besondere Weise. Auf dem Wasser vom Kanu aus.",
  "description": "Erlebe und entdecke Heilbronn vom Wasser aus. Fahre im Kanu auf dem Neckar durch Heilbronn und lass dir von deinem Gästeführer Interessantes zur Stadt und ihrer Geschichte erzählen. \nNoch nie Kanu gefahren?\nKein Problem, alle drei Touren sind absolut für Anfänger geeignet.\n\nDrei Touren stehen zur Auswahl:\n\n- Der Klassiker\n- Die Familientour\n- Die Tour am Abend",
  "amenities": ["Ausrüstung (Kanu, Paddel, Schwimmweste und Packsack)", "Stadtführer*in"],
  "more": "",
  "link": "https://www.heilbronn.de/tourismus/reise-und-erlebnisangebote/kanu-stadtrundfahrten.html?pk_campaign=themenkampagne_tmbw&pk_kwd=kanu-stadtrundfahrt",
  "price": "Ab 28 Euro pro Person (Kinder ab 22 Euro pro Person)",
  "priceRange": "10-50€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514521/tmbw/HN/HN_04/HN_04_01_gmsxsf.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514521/tmbw/HN/HN_04/HN_04_02_nzzrjh.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514522/tmbw/HN/HN_04/HN_04_03_lt9e6a.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514521/tmbw/HN/HN_04/HN_04_04_oyz2xz.jpg"]
}, {
  "id": "MA_01",
  "city": "Mannheim",
  "type": ["Tageserlebnis", "Kulinarik"],
  "people": ["Zu zweit", "Familie", "Gruppe"],
  "title": "NahTour - Mannheims Natur entdecken",
  "intro": "Entdecken Sie die grünen Oasen der Stadt und entspannen Sie bei einem Picknick",
  "description": "Rhein und Neckar, die großen Mannheimer Stadtparks und kleinere Grünflächen sowie Naturschutzgebiete und Wälder sind optimale Orte zum Ausspannen, für Spaziergänge oder für ein lauschiges Picknick. Der Herzogenriedpark ist eine grüne Oase im Stadtteil Neckarstadt-Ost, in der Sie es sich am Wasser und auf Wiesen gutgehen lassen können. Wohltuende Entspannung für Körper und Geist bietet die Kneipp-Anlage im Bambusgarten, das Rosarium mit über 100.000 Rosen lässt die Sinne erwachen.Mit einem liebevoll gepackten Picknickkorb von „Die Metzgerei“ können Sie bei einem Picknick am Rhein entspannt die vorbeifahrenden Schiffe beobachten.",
  "amenities": ["1 x Eintritt in den Herzogenriedpark", "1 x 1 Picknickkorb (Abholung in „Die Metzgerei“)", "1 x Gutscheinbuch pro Buchung", "10 % Rabatt auf alle Souvenirs der Tourist Information Mannheim"],
  "more": "",
  "link": "https://www.visit-mannheim.de/2-staedte-1-erlebnis/nahtour-buchen2?utm_source=tmbw&utm_medium=ad&utm_campaign=sommer2021",
  "price": "Preis pro Erwachsener mit Wellness-Korb: 37 Euro bei 2 Erwachsenen, 29 Euro bei 3 Erwachsenen ",
  "priceRange": "10-50€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623242074/tmbw/MA/MA_01/MA_01_01_emxnmd.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242074/tmbw/MA/MA_01/MA_01_02_kymrz3.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242074/tmbw/MA/MA_01/MA_01_03_le2ya1.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242074/tmbw/MA/MA_01/MA_01_04_vuveig.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242072/tmbw/MA/MA_01/MA_01_05_bkfgze.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242074/tmbw/MA/MA_01/MA_01_06_xfhmmi.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242072/tmbw/MA/MA_01/MA_01_07_sxnupv.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242074/tmbw/MA/MA_01/MA_01_08_ylzvnk.jpg"]
}, {
  "id": "MA_02",
  "city": "Mannheim",
  "type": ["Kultur", "Tageserlebnis", "Stadtführung"],
  "people": ["Zu zweit", "Familie", "Gruppe"],
  "title": "KulTour - Kreativität²",
  "intro": "Mannheim beeindruckt mit einem bunten Angebot an kulturellen Aktivitäten und Einrichtungen",
  "description": "Die Reiss-Engelhorn-Museen (rem) bilden im Herzen der Mannheimer Innenstadt ein eigenes Museumsviertel, in dem Sie spannende Kulturgeschichte erleben können. In der Ausstellung „Ägypten – Land der Unsterblichkeit“ entdecken Sie das faszinierende Reich der Pharaonen mitten in Mannheim. Mit dem im Paket enthaltenen Audioguide erfahren Sie Spannendes über das Alltagsleben im alten Ägypten, die Stellung des Pharaos und seines Beamtenstaates, den aufwändigen Totenkult und die weitverzweigte Götterwelt. Kinder können mit den Rätsel- und Entdeckerheften eigenständig interessante Themen und Objekte aus den Ausstellungen entdecken (kostenfrei zum Download oder an der Museumskasse).\nFür Geschichtsinteressierte führt kein Weg am Schloss Mannheim vorbei, dem größten Barockschloss Europas nach Versailles. In den aufwendig restaurierten Prunkräumen begeben Sie sich auf eine Zeitreise ins kurfürstliche Mannheim. \nDen kreativen Herzschlag der Stadt erleben Sie bei einer individuellen Stadtführung durch die einzigartige Open Urban Art Gallery Mannheims - STADT.WAND.KUNST. Vielleicht haben Sie ja auch Glück und können bei der Entstehung eines neuen Murals live dabei sein! Denn jeden Sommer lädt STADT.WAND.KUNST unterschiedliche Streetart-KünstlerInnen nach Mannheim ein: Egal ob nationale Newcomer, internationale Stars oder regionale NachwuchskünstlerInnen – auch in diesem Jahr werden sie wieder Mannheims Wände in großartige Kunstwerke verwandeln.\nBei Buchung unseres Paketes haben Sie für sich, Ihre Familie oder Freunde eine*n eigene*n Gästeführer*in und können Tag und Uhrzeit frei wählen.",
  "amenities": ["1 x Individuelle Stadtführung „STADT.WAND.KUNST – Quadrate“, Dauer: ca. 1,5 Stunden", "1 x Eintritt Museum Weltkulturen D5 (rem) mit Audio-Guide", "1 x Eintritt in das Schloss Mannheim", "1 x Gutscheinbuch pro Buchung", "10 % Rabatt auf alle Artikel des Museumsshop der"],
  "more": "",
  "link": "https://www.visit-mannheim.de/2-staedte-1-erlebnis/kultour-buchen?utm_source=tmbw&utm_medium=ad&utm_campaign=sommer2021",
  "price": "Preis pro Erwachsener: 64 Euro\nPreis pro Kind (6-14 Jahre): 5 Euro",
  "priceRange": "50-100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623242101/tmbw/MA/MA_02/MA_02_01_dcbndt.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242100/tmbw/MA/MA_02/MA_02_02_khtynj.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242100/tmbw/MA/MA_02/MA_02_03_xhnd5b.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242101/tmbw/MA/MA_02/MA_02_04_qkzaqu.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242100/tmbw/MA/MA_02/MA_02_06_xsdusf.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242103/tmbw/MA/MA_02/MA_02_07_bqysju.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242104/tmbw/MA/MA_02/MA_02_08_mliirz.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242105/tmbw/MA/MA_02/MA_02_09_o2zzrw.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242104/tmbw/MA/MA_02/MA_02_10_ezayjg.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242106/tmbw/MA/MA_02/MA_02_11_gblzzs.jpg"]
}, {
  "id": "MA_03",
  "city": "Mannheim",
  "type": ["Kulinarik", "Tageserlebnis", "Übernachtung"],
  "people": ["Zu zweit", "Einzeln", "Gruppe"],
  "title": "Happy Weekend in Mannheim",
  "intro": "Verbringen Sie Ihr persönliches Happy Weekend in der lebendigen Metropole",
  "description": "Entdecken Sie Mannheim, die bunte und lebendige Metropole voller Kontraste in der Rhein-Neckar-Region. Hier werden Sie viel erleben – nur keine Langeweile.  Zahlreiche Sehenswürdigkeiten wie z.B. das Mannheimer Barockschloss, der Luisenpark, der Wasserturm und das Nationaltheater warten auf Sie. Mannheims beliebte Citymeile „Planken“ lädt zum Bummeln und Shoppen ein, NachtschwärmerInnen finden außergewöhnliche Cafés und stylische Clubs. Alles nur einen Steinwurf vom Dorint Hotel entfernt! ",
  "amenities": ["2 Übernachtungen inklusive reichhaltigem Frühstücksbuffet", "1 x Welcome-Cocktail", "1 x Kulinarisches 3-Gang-Menü am Abend"],
  "more": "",
  "link": "https://hotel-mannheim.dorint.com/de/arrangements/happy-weekend/",
  "price": "ab 145 € p.P.",
  "priceRange": ">100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623242305/tmbw/MA/MA_03/MA_03_01_k3iblg.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242305/tmbw/MA/MA_03/MA_03_02_zi643i.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242305/tmbw/MA/MA_03/MA_03_03_vquoxa.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242305/tmbw/MA/MA_03/MA_03_04_wufpab.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242305/tmbw/MA/MA_03/MA_03_05_xtb61x.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242303/tmbw/MA/MA_03/MA_03_06_oeijxm.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242304/tmbw/MA/MA_03/MA_03_07_zdla67.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242305/tmbw/MA/MA_03/MA_03_08_di2cbk.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514643/tmbw/MA/MA_03/MA_03_09_n8jj11.jpg"]
}, {
  "id": "MA_04",
  "city": "Mannheim",
  "type": ["Kultur", "Tageserlebnis"],
  "people": ["Zu zweit", "Einzeln", "Gruppe"],
  "title": "Mannheim und UNESCO Creative Cities ",
  "intro": "Entdecken Sie das UNESCO-Kulturtrio mit Mannheim, Karlsruhe und Heidelberg",
  "description": "Ob Merton oder Mozart: Mannheim bietet eine musikalische Vielfalt, wie sie sonst nur in den großen Metropolen der Welt zu finden ist. Zahlreiche musikalische Einflüsse begegnen sich hier und prägen eine einzigartige Musikszene. Ob Techno, Jazz, Pop oder Indie – Musik ist in Mannheim vielseitig, international geprägt und bietet Highlights für jeden Geschmack. Festivals wie Enjoy Jazz, Time Warp oder Maifeld Derby und international bekannte Stars, die hier regelmäßig zu Gast sind, locken Menschen aus ganz Europa nach Mannheim. Mit der einzigartigen Popakademie und einer innovativen Musikwirtschaft avancierte die Stadt zur „UNESCO City of Music“ – weltweit gibt es nur wenige Städte,die diesen Titel tragen. Erleben Sie Musik auf eine andere Art im Hotel Staytion. Jede der 6 Etagen ist einer anderen Band oder Musikrichtung gewidmet und die Zimmer sind mit zahlreichen Bildern und Musik ausgestattet. Bei der Stadtführung tauchen Sie tiefer ein in die bunte Musikszene Mannheims.\n",
  "amenities": ["3 Übernachtungen im Einzel- oder Doppelzimmer inkl. Frühstück\n", "2x Stadtführung, eine in Heidelberg und eine in Mannheim ", "1 x Heidelberg Karte ", "Besichtigung des ZKM / Zentrum für Kunst und Medien in Karlsruhe"],
  "more": "",
  "link": "https://www.karlsruhe-erleben.de/karlsruhe/offer/detail/FIT00020070733670846",
  "price": "360 € für drei Übernachtungen und Nebenleistungen",
  "priceRange": ">100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623242436/tmbw/MA/MA_04/MA_04_01_kq8j6a.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242437/tmbw/MA/MA_04/MA_04_02_pt87ut.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242438/tmbw/MA/MA_04/MA_04_03_elb2ne.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623242437/tmbw/MA/MA_04/MA_04_04_wvoftt.jpg"]
}, {
  "id": "S_01",
  "city": "Stuttgart",
  "type": ["Stadtführung", "Tageserlebnis", "Kultur", "Wein"],
  "people": ["Zu zweit", "Einzeln", "Gruppe", "Familie"],
  "title": "Stuttgart bequem entdecken",
  "intro": "Sightseeing entlang der wichtigsten Sehenswürdigkeiten Stuttgarts",
  "description": "Entdecke die bedeutendsten Sehenswürdigkeiten Stuttgarts - und steige aus und wieder zu, wie es dir gefällt! Jedes Hop-on/Hop-off Ticket gilt 24 Stunden - und lässt dir genügend Spielraum für individuelle Stadterkundungen. \n\nDu kannst zwischen drei Routen wählen: \n- Auf unserer BLAUEN TOUR geht es über die Stuttgarter Innenstadt in Richtung Neckar und Wilhelma, vorbei am Mercedes-Benz-Museum bis in die Weinberge. \n- Die GRÜNE TOUR bringt euch in den Stuttgarter Süden und Westen. Auf dem Weg liegen der Fernsehturm, schöne Aussichtspunkte und die urige Standseilbahn.\n- Auf der WEINTOUR erwartet euch eine herrliche Fahrt in die Weinlandschaft Stuttgarts: Vom Mercedes-Benz-Museum aus führt euch die Tour in die Weinberge bis hoch zur Grabkapelle auf dem Württemberg.",
  "amenities": "Hop-on/Hop-off Ticket 24 Stunden gültig",
  "more": "",
  "link": "https://www.stuttgart-tourist.de/stuttgart-buchen/stuttgart-citytour",
  "price": ["BLAUE und GRÜNE TOUR:\nErwachsene 18,00 €\nErwachsene mit StuttCard 14,00 €\nKinder (4-14 Jahre) 5,00 €\nPersonen mit Schwerbehinderten-ausweis ab 80% 14,00 € ", "WEINTOUR: Erwachsene 12,00 € Erwachsener mit StuttCard 10,00 € Kind (4 - 14 Jahre) 5,00 € Personen mit Schwerbehinderten-ausweis ab 80 % 10,00 €", "KOMBITICKET (2 Touren): Erwachsene 28,00 € Erwachsener mit StuttCard 22,00 € Kind (4 - 14 Jahre) 10,00 € Personen mit Schwerbehinderten-ausweis ab 80 % 22,00 €"],
  "priceRange": "10-50€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514748/tmbw/S/S_01/S_01_02_oyenaf.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514748/tmbw/S/S_01/S_01_02_oyenaf.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514748/tmbw/S/S_01/S_01_03_rychot.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514748/tmbw/S/S_01/S_01_04_q5qsko.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514748/tmbw/S/S_01/S_01_05_tjlmmx.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514748/tmbw/S/S_01/S_01_06_wdjmqp.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514749/tmbw/S/S_01/S_01_07_mnucja.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514749/tmbw/S/S_01/S_01_08_zk7hyf.jpg"]
}, {
  "id": "S_02",
  "city": "Stuttgart",
  "type": ["Stadtführung", "Tageserlebnis", "Kultur", "Wein"],
  "people": ["Zu zweit", "Einzeln", "Gruppe", "Familie"],
  "title": "Weinprobe im Weinbaumuseum",
  "intro": "Genussvoll ins Wochenende starten",
  "description": "Starte doch mal relaxter ins Wochenende: Mit einer genussvollen Freitagsweinprobe in der Vinothek des Weinbaumuseums Stuttgart. Ein Experte macht dich mit drei exzellenten Stuttgarter Weinen bekannt und vermittelt dir nebenbei hochinteressante Details über den Weinbau im mittleren Neckarraum. Ein Vergnügen, bei dem du anschließend mit deinen Weinkenntnissen punkten kannst.",
  "amenities": "3er Weinprobe von ausgewählten Weinen und kleinem Snackteller",
  "more": "",
  "link": "https://www.stuttgart-tourist.de/e-freitagsweinprobe-werden-sie-zum-weinkenner#2021-05-07",
  "price": "19,50€",
  "priceRange": "10-50€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514756/tmbw/S/S_02/S_02_01_hxvyqs.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623244441/tmbw/S/S_02/S_02_05_yo0mfl.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514756/tmbw/S/S_02/S_02_03_ssivub.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514756/tmbw/S/S_02/S_02_04_u8xrcs.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514757/tmbw/S/S_02/S_02_02_pr7bxi.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514756/tmbw/S/S_02/S_02_06_vp0im9.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514756/tmbw/S/S_02/S_02_07_awsat1.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514757/tmbw/S/S_02/S_02_08_giyezu.jpg"]
}, {
  "id": "U_01",
  "city": "Ulm",
  "type": ["Übernachtung", "Stadtführung", "Kulinarik", "Tageserlebnis"],
  "people": ["Einzeln", "Zu zweit"],
  "title": "Ulmer Impressionen ",
  "intro": "Die ganze Palette Ulm – zwei Nächte, vier Gänge und unzählige Erlebnisse ",
  "description": "Lerne Ulm mit allen Sinnen kennen! Du übernachtest zwei Mal zentral im Akzent Hotel Roter Löwe, genießt ein regionales 4-Gang Menü und erlebst die wichtigsten Sehenswürdigkeiten dank der UlmCard gratis. Damit und uns nicht vergisst gibt´s sogar ein paar kleine Souvenirs. Wir können es kaum erwarten bis du uns besuchst. ",
  "amenities": ["ein regionales 4-Gang Menü", "2x Übernachtung im Akzent Hotel Roter Löwe", "1x Ulm Card für zwei Tage"],
  "more": "",
  "link": "https://www.hotel-roter-loewe.de/preise---pauschalen.html",
  "price": "149 EUR pro Person ",
  "priceRange": ">100€",
  "pictures": "https://res.cloudinary.com/viewyork-media/image/upload/v1621514792/tmbw/U/U_01/U_01_12_l86pcn.jpg"
}, {
  "id": "U_02",
  "city": "Ulm",
  "type": "Stadtführung",
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Öffentliche Stadtführungen",
  "intro": "Mit unseren ausgebildeten Gästeführern durch Ulm/Neu-Ulm",
  "description": "Schließe dich unserer öffentlichen Stadtführung mit Besichtigung des Ulmer Münsters an. Wir zeigen dir die Highlights: Ulmer Münster, historisches Rathaus, Neue Mitte und natürlich das Fischer- und Gerberviertel. Von April bis Oktober sogar zweimal täglich.",
  "amenities": "",
  "more": "",
  "link": "https://tourismus.ulm.de/de/entdecken/sehen-und-erleben/stadtfuerungen/oeffentliche-stadtfuehrungen/#/erlebnisse/ULM/a09cf94d-0bc4-4b06-92db-f29bda5fb243/altstadt--und-muensterfuehrung--oefftl--",
  "price": "kostenfrei für Kinder, EUR 9 für Erwachsene, EUR 5 für Studenten, Schüler, Schwerbehinderte",
  "priceRange": "0-10€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623337317/tmbw/U/U_02/U_02_01_o5dhzy.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514803/tmbw/U/U_02/U_02_02_eetd35.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514804/tmbw/U/U_02/U_02_03_njbpyp.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514804/tmbw/U/U_02/U_02_04_afjzt9.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514804/tmbw/U/U_02/U_02_05_lnlpr4.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514804/tmbw/U/U_02/U_02_06_xob9eq.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514804/tmbw/U/U_02/U_02_07_r5oijs.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514804/tmbw/U/U_02/U_02_08_somywl.jpg"]
}, {
  "id": "U_03",
  "city": "Ulm",
  "type": "Stadtführung",
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Schifffahrt durch Ulm",
  "intro": "Geniessen Sie Ihre Fahrt auf dem Ulmer Spatz!",
  "description": "Kapitäne, nehmt uns mit auf die Reise! Die Anlegestellen liegen beim Metzgerturm und in der Friedrichsau, Ulms großem Stadtpark. Die Crew besteht aus Menschen mit und ohne Behinderung, aus lauter Ulm-Botschaftern sowie mitreißenden Anekdoten-Erzählern. Für Kinder haben sie ein besonderes Herz. Auf Wunsch dürfen diese selbst einmal das Steuerrad in die Hand nehmen.",
  "amenities": "",
  "more": "",
  "link": "https://ulmer-schifffahrt.de/kalender/",
  "price": "kostenfrei für Kinder, EUR 9,50 für Erwachsene, EUR 6,50 für Studenten, Schüler, Schwerbehinderte",
  "priceRange": "0-10€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514811/tmbw/U/U_03/U_03_01_m25yil.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514811/tmbw/U/U_03/U_03_02_lzj1dn.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514811/tmbw/U/U_03/U_03_03_i2oimd.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514811/tmbw/U/U_03/U_03_04_zrcjzl.jpg"]
}, {
  "id": "U_04",
  "city": "Ulm",
  "type": "Tageserlebnis",
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Birdly - Virtuelle Realität",
  "intro": "Der Traum vom Fliegen: Virtual Reality zum Abheben!",
  "description": "In Ulm kannst virtuelle Realität auf einzigartiger Weise erleben: Mit dem innovativen Simulator ›Birdly‹ fliegst du wie ein Vogel über die Dächer Ulms im Jahr 1890. Du steigst auf und ab über der virtuellen Stadt, die dir lebensecht in der 3D-Brille erscheint. Aber nicht nur das: mit deinem Körper steuerst du den einmaligen Ganzkörperflugsimulator.",
  "amenities": "",
  "more": "",
  "link": "https://ulmstories.reservix.de/#2021-03-12",
  "price": "pro Flug EUR 5",
  "priceRange": "0-10€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514819/tmbw/U/U_04/U_04_01_knn4wy.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514819/tmbw/U/U_04/U_04_02_gjuf1r.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514819/tmbw/U/U_04/U_04_03_nfw2cf.jpg"]
}, {
  "id": "F_01",
  "city": "Freiburg",
  "type": ["Tageserlebnis", "Kulinarik", "Stadtführung"],
  "people": "Gruppe",
  "title": "Freiburg erleben und geniessen",
  "intro": "Bunter Münstermarkt, fantastische Ausblicke und regionale Kostproben",
  "description": "Nach einem gemütlichen Frühstück steht heute Freiburg auf Ihrem Tagesprogramm. Wir starten mit einem gemeinsamen Spaziergang über den bunten Münstermarkt rund um Freiburgs Wahrzeichen. Danach geht es mit der Schlossbergbahn hinauf zum Schlossberg. Oben angekommen werden Sie mit fantastischen Aussichten auf die Stadt und das Rheintal belohnt. Der Schlossberg lädt nicht nur zum Wandern, Entdecken und Verweilen ein, er bietet auch eine ausgezeichnete Gastronomie. Zurück in der Freiburger Altstadt geht es nun durch die malerische Fischerau und Gerberau zur Stadtmitte. Dort stehen Ihnen nun Freiburgs Museen* zur Wahl, die viel über die Stadt, die Kunst, die Region und die Natur erzählen. Eine kulinarische Stadtführung mit allerlei regionale Kostproben unterwegs sowie ein Abendessen mit regionalen Spezialitäten am Freiburger Münsterplatz krönen Ihren Tag.",
  "amenities": ["Fahrt mit der Schloßbergbahn auf den Schlossberg", "Besuch in einem der Freiburger Stadtmuseum", "Kulinarische Stadtführung mit regionalen Kostproben", "Regionales Abendessen am Münsterplatz"],
  "more": "",
  "link": "https://schwarzwald-connection.de/angebot_gruppen_fwtm.pdf",
  "price": "15-30 Personen, 4,5- 7 Stunden, Kosten pro Person: 89,00 €",
  "priceRange": "50-100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623752358/tmbw/F/F_01/F_01_03_esgcie.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514339/tmbw/F/F_01/F_01_02_tccoi0.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514339/tmbw/F/F_01/F_01_03_cxnnlm.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514339/tmbw/F/F_01/F_01_04_ew1mvz.jpg"]
}, {
  "id": "F_02",
  "city": "Freiburg",
  "type": ["Tageserlebnis", "Kulinarik", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit"],
  "title": "Freiburgs Hausberg Schauinsland entdecken",
  "intro": "Bergbüffet, Wanderführer, Bauernhofmuseum und gehobene Küche",
  "description": "Nach einer gemütlichen Anreise zur Bergstation der Schauinslandbahn geht es schon bald zur Stärkung ins Bergrestaurant auf 1200 Höhe. Das Bergbüffet meint es gut mit Ihnen: Großes Bauernbrot, kleine Brötchen – alles frisch aus dem Ofen. Konfitüren, Käse, Fleisch- und Wurst-Spezialitäten aus der Region. Ausgesuchtes rund um Obst, Joghurt, Milch und Säfte. Und Kaffee und Tee soviel Sie mögen. Nach der Stärkung werden Sie bereits vom ortskundigen Wanderguide erwartet. Erfahren Sie viel Wissenswertes und Interessantes auf Ihrer Wanderung zum Bauernhausmuseum Schniederlihof. Hier erwartet Sie ein herzlicher Empfang im über 400 Jahre alten Hof. Sachkundig und liebevoll wird Ihnen vermittelt, wie mit Kuchi, dem Schniedesel, der Bühni und der guten Stub mit Herrgottswinkel das früher oft sehr harte Leben der Schwarzwälder Bergbauern ausgesehen hat. Den perfekten Ausklang des Tages genießen Sie im Hotel Halde – mit unbeschreiblichen Service, regionalen Spezialitäten und einer entspannten Atmosphäre – hier bleiben keine Wünsche offen. ",
  "amenities": ["Fahrt mit dem ÖPNV zur Schauinslandbahn und zurück", "Berg- und Talfahrt mit der Schauinslandbahn", "Bergwelt-Fruhstücks-Büfett", "Ortskundiger Wanderguide", "Besuch und Führung im Bauernhofmuseum Schniederlihof", "Gemütliche Einkehr im Hotel Halde (Sitzplatz-Reservierung)"],
  "more": "",
  "link": "https://schwarzwald-connection.de/angebot_individuell_fwtm.pdf",
  "price": "1-2 Personen, 4,5- 7 Stunden, Kosten pro Person: 89,00€",
  "priceRange": "50-100€",
  "pictures": "https://res.cloudinary.com/viewyork-media/image/upload/v1623752419/tmbw/F/F_03/F_04_03_zzoen2.jpg"
}, {
  "id": "F_03",
  "city": "Freiburg",
  "type": ["Übernachtung", "Kulinarik", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit"],
  "title": "Freiburger Gipfelglück – Wellness inklusive",
  "intro": "2-Tages-Angebot: Aktiv entschleunigen",
  "description": "Aktiv entschleunigen in der Schwarzwald-Hauptstadt heißt es bei einer aussichtsreichen Rundwanderung auf Freiburgs Hausberg, dem Schauinsland. Das Erlebnis beginnt bereits bei der Bergfahrt mit Deutschlands ältester Umlaufseilbahn. Und Entspannung verspricht im Anschluss ein Bad in Freiburgs Keidel-Therme.",
  "amenities": ["2 Übernachtungen im DZ inkl. Frühstück im 4*-Dorint Thermenhotel Freiburg", "Lunchpaket", "Welcome-Ticket (3-Tage-Regio-Ticket ÖPNV inkl. Schauinslandbahn)", "Wandervorschlag auf dem Hausberg Schauinsland mit Tipps für Sehenswürdigkeiten und Wanderkarte Schauinsland", "Audio-Lausch-Tour Schauinsland", "1 Eintritt in die Thermen des Keidel Bads"],
  "more": "https://hotel-freiburg.dorint.com/de/arrangements/freiburger-gipfel-glueck/?etcc_cmp=Freiburg&etcc_med=Gipfel-Glueck-Arrangement-TMBW&etcc_par=HON-Service&etcc_ctv=Webseite&et_cmp_seg4=DE",
  "link": "https://be.synxis.com/?&chain=22066&config=Dorint&level=chain&locale=de-DE&theme=Dorint&brand=Dorint&src=FRI-Package&promo=Package-TMBW&rate=PF&hotel=77509&adult=2&nights=2",
  "price": "252,00 € / p.P.",
  "priceRange": ">100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514350/tmbw/F/F_02/F_02_01_tlneyt.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514362/tmbw/F/F_03/F_03_02_mp740o.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514362/tmbw/F/F_03/F_03_01_zkpxps.jpg"]
}, {
  "id": "F_04",
  "city": "Freiburg",
  "type": ["Übernachtung", "Kulinarik", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit"],
  "title": "Bike-Zeit in Freiburg – Wellness inklusive",
  "intro": "2-Tages-Angebot: Lieblingsplätze mit dem E-Bike entdecken",
  "description": "Erkunden Sie die Schwarzwald-Hauptstadt Freiburg per E-Bike oder Mountain-Bike. Ob relaxtes Radeln entlang dem Dreisamufer, Entdeckung der Altstadt und moderner Green-City-Architektur oder Genuss-Tour durch Freiburgs Weinberge: In kaum einer anderen Stadt treffen Sie auf so viel Wohlfühl-Lifestyle und Lässigkeit, verbunden mit sportlicher Freizeitaktivität. Und die Beine erholen sich ganz rasch wieder in den heißen Quellen von Freiburgs Keidel-Therme.",
  "amenities": ["2 Übernachtungen im DZ inkl. Frühstück im 4*-Dorint Thermenhotel Freiburg", "Lunchpaket", "Radtouren-Vorschlag Dreisamradweg / Tuniberg Höhenweg", "Radkarte für Ihre Tour", "1 Eintritt in die Thermen des Keidel Bads", "1 Tag E-Bike- oder Mountain-Bike-Verleih"],
  "more": "https://hotel-freiburg.dorint.com/de/arrangements/e-bike-zeit-in-freiburg/?etcc_cmp=Freiburg&etcc_med=E-Bike-Arrangement-TMBW&etcc_par=HON-Service&etcc_ctv=Webseite&et_cmp_seg4=DE",
  "link": "https://be.synxis.com/?&chain=22066&config=Dorint&level=chain&locale=de-DE&theme=Dorint&brand=Dorint&src=FRI-Package&promo=Package-TMBW&rate=PE&hotel=77509&adult=2&nights=2",
  "price": "251,00 € / p.P.",
  "priceRange": ">100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514373/tmbw/F/F_04/F_04_01_dympel.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514373/tmbw/F/F_04/F_04_02_fv4fkx.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623244351/tmbw/F/F_04/F_04_03_bg1v4l.jpg"]
}, {
  "id": "HD_01",
  "city": "Heidelberg",
  "type": ["Tageserlebnis", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Entspannt Heidelberg erkunden",
  "intro": "Stadtrundfahrt mit Schlossführung",
  "description": "Freier Blick auf die „Bühne Heidelberg” – erster Akt: der Blick auf das romantische Schloss, das majestätisch über dem Karlsplatz thront. Es folgt eine gemütliche Stadtrundfahrt in Begleitung eines Gästeführers entlang des Neckars vorbei an der Alten Brücke. Der zweite Akt führt hinauf zum Heidelberger Schloss – bei einer Außenführung bringt Ihnen Ihr Gästeführer die Geschichte des weltberühmten Bauwerks näher, Sie besichtigen den Innenhof und das größte Weinfass der Welt. Nach der Führung können Sie das Deutsche Apotheken-Museum besuchen und anschließend mit der Bergbahn zurück in die Altstadt (Talstation Kornmarkt) fahren (Ticket ist inklusive).",
  "amenities": "Ticket für Bergbahn",
  "more": "",
  "link": "https://tportal.toubiz.de/heidelberg-fuehrungen/offer/detail/FIT00020070298566625",
  "price": "27 € Erw./24 € ermäßigt inkl. Schlossticket",
  "priceRange": "10-50€",
  "pictures": "https://res.cloudinary.com/viewyork-media/image/upload/v1621514423/tmbw/HD/HD_01/HD_01_01_msqyi0.jpg"
}, {
  "id": "HD_02",
  "city": "Heidelberg",
  "type": ["Tageserlebnis", "Stadtführung", "Übernachtung"],
  "people": ["Einzeln", "Zu zweit"],
  "title": "Heidelberg im Sommer",
  "intro": "Sommerspeziel - 3 Nächte bleiben, 2 bezahlen (23.07. - 29.08.2021)   ",
  "description": "Ein Sonnenbad auf der Neckarwiese genießen oder bei lauen Abendtemperaturen die romantische Altstadt erkunden. In der warmen Jahreszeit blüht das Leben in Heidelbergs verwinkelten Gassen: Die vielen gemütlichen Cafés und Kneipen bieten Plätze an der Sommerluft und mitten im emsigen Treiben unserer Stadt. Eine Vielzahl kultureller Highlights machen den Sommer in Heidelberg zum unvergesslichen Erlebnis. Und weil die Sonne bei uns so viel schöner scheint, geht bei diesem Arrangement die dritte Übernachtung auf unsere Kosten.",
  "amenities": ["1, 2 oder 3 Übernachtungen mit Frühstück im Einzel- oder Doppelzimmer in einem Hotel der Kategorie Komfort oder First Class", "HeidelbergCARD für die Dauer des Aufenthaltes", "Teilnahme am öffentlichen Altstadtrundgang (1,5 Std.)", "Ticket für die Fahrt mit dem Solarschiff „Neckarsonne“"],
  "more": "",
  "link": "https://www.heidelberg-marketing.de/suchen-buchen/pauschalreisen/sommerspezial.html",
  "price": "Kategorie Komfort: 180 € p.P. im Doppelzimmer/   240 € p.P. im Einzelzimmer, Kategorie First Class WoEnde:                 205 € p.P. im Doeppelzimmer/ 310 € p.P. im Einzelzimmer",
  "priceRange": ">100€",
  "pictures": "https://res.cloudinary.com/viewyork-media/image/upload/v1621514434/tmbw/HD/HD_02/HD_02_01_sgplud.jpg"
}, {
  "id": "HD_03",
  "city": "Heidelberg",
  "type": ["Tageserlebnis", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Heidelberg und UNESCO Creative Cities\n\n",
  "intro": "Heidelberg – literarische Vielfalt und Produktivität",
  "description": "3 Städte in 3 Tagen\n\nHeidelberg, Mannheim und Karlsruhe – ein „UNESCO-Dreieck“, das mit einem außergewöhnlichen Kulturerlebnis punkten kann! Denn alle drei Städte im Südwesten sind als Teil des UNESCO-Netzwerks gewählt worden. Erleben Sie also Heidelberg als Stadt der Literatur, Mannheim als Stadt der Musik und Karlsruhe als Stadt der Medienkunst – die UNESCO Creative Cities freuen sich schon auf Ihren Besuch!\n\nLiteratur ist in Heidelberg allgegenwärtig. Beim Spaziergang durch die Stadt findet man an jeder Ecke Buchhandlungen, Antiquariate, Verlage und Bibliotheken. Es vergeht kaum ein Tag ohne literarische Veranstaltung, kein Sommer ohne das Literaturfestival Heidelberger Literaturtage, kein Jahr ohne literarische Preisträger.",
  "amenities": ["3 Übernachtungen im Einzel- oder Doppelzimmer, inklusive Frühstück", "HDCard für 2 Tage", "2 Stadtführungen (jeweils eine in Mannheim und eine in Heidelberg)"],
  "more": "",
  "link": "https://www.karlsruhe-erleben.de/karlsruhe/offer/detail/FIT00020070733670846",
  "price": "350,00 € pro Person im Doppelzimmer",
  "priceRange": ">100€",
  "pictures": "https://res.cloudinary.com/viewyork-media/image/upload/v1621514446/tmbw/HD/HD_03/HD_03_01_c7qxzo.jpg"
}, {
  "id": "HD_04",
  "city": "Heidelberg",
  "type": ["Tageserlebnis", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Heidelberg per Bike",
  "intro": "Geführte Radtour durch Heidelberg",
  "description": "Bei einer geführten Radtour streifen wir die Heidelberger Altstadt und besuchen den Stadtteil Neuenheim, das Neuenheimer Feld mit Botanischem Garten und den international renommierten Instituten und Kliniken sowie den Forschungs-Campus der Ruprecht-Karls-Universität.\nWir fahren durch das Handschuhsheimer Feld weiter nach Handschuhsheim, dem ältesten Stadtteil Heidelbergs mit der berühmten Tiefburg und zurück zur Altstadt, wo der einzigartige Blick von der Alten Brücke auf das Heidelberger Schloss und die Altstadt den krönenden Abschluss bildet. Streckenlänge: ca. 25km, Profil: eine steilere Steigung, Möglichkeit zum Picknick oder Einkehr, Dauer: ca. 3 Stunden ",
  "amenities": "",
  "more": "",
  "link": "https://tportal.toubiz.de/heidelberg-fuehrungen/guide/detail/FIT00020070300786229",
  "price": "130 € inkl. privatem Guide für 1-10 Personen (zzgl. 18 € pro Person für Fahrrad und Helm), max. 10 Personen, buchbar: April - Oktober",
  "priceRange": ">100€",
  "pictures": "https://res.cloudinary.com/viewyork-media/image/upload/v1621514458/tmbw/HD/HD_04/HD_04_01_twlnk6.jpg"
}, {
  "id": "K_01",
  "city": "Karlsruhe",
  "type": ["Tageserlebnis", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Citytour Karlsruhe",
  "intro": "Tour mit dem roten Doppeldeckerbus",
  "description": "Der Klassiker unter den Sightseeingtouren. Steigen Sie ein und entdecken Sie die bedeutendsten Sehenswürdigkeiten in Karlsruhe!",
  "amenities": "",
  "more": "",
  "link": "https://www.karlsruhe-erleben.de/citytour?utm_source=TMBW%20Social%20Media&utm_medium=Ad&utm_campaign=TMBW%20Social%20Media#/",
  "price": "18€ Erwachsene; Kinder 5€",
  "priceRange": "10-50€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514553/tmbw/K/K_01/K_01_01_yue2eq.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514553/tmbw/K/K_01/K_01_02_vbo3il.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514554/tmbw/K/K_01/K_01_03_aembvu.jpg"]
}, {
  "id": "K_02",
  "city": "Karlsruhe",
  "type": ["Tageserlebnis", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Recht-Unrecht Tour",
  "intro": "Abenteuertour auf den Spuren des Rechts über eine App",
  "description": "",
  "amenities": "",
  "more": "",
  "link": "https://www.karlsruhe-erleben.de/Tatort-Recht?utm_source=TMBW%20Social%20Media&utm_medium=Ad&utm_campaign=TMBW%20Social%20Media",
  "price": "18€ Erwachsene; Kinder 5€",
  "priceRange": "10-50€",
  "pictures": ""
}, {
  "id": "K_03",
  "city": "Karlsruhe",
  "type": ["Tageserlebnis", "Stadtführung", "Übernachtung", "Kultur"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Karlsruhe und UNESCO Creative Cities ",
  "intro": "Entdecken Sie das UNESCO-Kulturtrio mit Mannheim, Karlsruhe und Heidelberg",
  "description": "Karlsruhe ist eine Stadt, in der Medienkunst in ihren verschiedenen Formen zum Leben gehört, sowohl als boomender IT- und Wissenschaftsstandort als auch als Stadt der Kultur und Kreativität. Karlsruhe blickt außerdem auf eine lange Tradition als Stadt des Rechts, der Grundrechte und der Demokratie zurück. Besonders zur Realisierung medienkünstlerischer Werke, die oft durch digitale Teilhabe, Interaktion und Partizipation geprägt sind oder sich mit kritischen Fragestellungen beschäftigen, ist dies eine wichtige Voraussetzung.",
  "amenities": ["3 Übernachtungen im Einzel- oder Doppelzimmer inkl. Frühstück\n", "2x Stadtführung, eine in Heidelberg und eine in Mannheim ", "1 x Heidelberg Karte Besichtigung des ZKM / Zentrum für Kunst und Medien in Karlsruhe"],
  "more": "",
  "link": "https://www.karlsruhe-erleben.de/karlsruhe/offer/detail/FIT00020070733670846?utm_source=TMBW%20Social%20Media&utm_medium=Ad&utm_campaign=TMBW%20Social%20Media",
  "price": "350 € pro Einheit",
  "priceRange": "10-50€",
  "pictures": "https://res.cloudinary.com/viewyork-media/image/upload/v1621514565/tmbw/K/K_03/K_03_01_cttcll.jpg"
}, {
  "id": "K_04",
  "city": "Karlsruhe",
  "type": ["Tageserlebnis", "Stadtführung"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Frische Luft-/Picknick",
  "intro": "",
  "description": "",
  "amenities": "",
  "more": "",
  "link": "https://www.karlsruhe-erleben.de/karlsruhe/package/detail1/FIT00020070881520322",
  "price": "",
  "priceRange": "",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623749845/tmbw/K/K_04/K_04_01_upq2l3.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623749846/tmbw/K/K_04/K_04_02_jdnzue.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623749846/tmbw/K/K_04/K_04_03_a1d9u2.jpg"]
}, {
  "id": "P_01",
  "city": "Pforzheim",
  "type": ["Tageserlebnis", "Kultur"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Gasometer Pforzheim",
  "intro": "Das weltgrößte 360° Panorama",
  "description": "Zur Zeit ist das fernweh besonders groß. Wie schön wäre es nach Australien zu reisen und die magische Unterwasserwelt des Great Barrier Reef zu genießen? Im Gasometer Pforzheim ist das möglich! Das weltgrößte 360° Panorama des Künstlers Yadegar Asisi zeigt die faszinierende Wunderwelt eines Korallenriffs. Ein Erlebnis für die ganze Familie.",
  "amenities": "",
  "more": "",
  "link": "https://gasometer-pforzheim.regiondo.de/kategorien",
  "price": "ab 10,00€",
  "priceRange": "0-10€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514694/tmbw/PF/PF_01/PF_01_01_adz2bv.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514694/tmbw/PF/PF_01/PF_01_02_fqoy1z.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514694/tmbw/PF/PF_01/PF_01_03_broudk.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514694/tmbw/PF/PF_01/PF_01_04_qswabb.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514694/tmbw/PF/PF_01/PF_01_05_op5cis.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514695/tmbw/PF/PF_01/PF_01_06_lbyzek.jpg"]
}, {
  "id": "P_02",
  "city": "Pforzheim",
  "type": ["Stadtführung", "Kultur"],
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Pforzheim per Augmented Reality",
  "intro": "Stadtführung der besonderen Art.",
  "description": "Mit den spannenden Touren der Future History App kann Pforzheim, die Goldstadt, entspannt entdeckt werden. Dank Augmented Reality wird die Schönheit der einstigen Jugendstil-Perle durch historische Aufnahmen sichtbar. Interessante Infos zu den Sehenswürdigkeiten, der Architektur, Glaubensstätten oder den Wasserperlen der Stadt, gibt es ebenfalls zum Anhören oder Lesen. Die Touren sind perfekt für die Vorbereitung auf einen Besuch zuhause oder beim Bummeln durch die Stadt.",
  "amenities": "",
  "more": "",
  "link": "https://www.pforzheim.de/tourismus/stadtfuehrungen/digitale-stadtfuehrungen-und-erlebnisse.html",
  "price": "ab 1,09€",
  "priceRange": "0-10€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514704/tmbw/PF/PF_02/PF_02_01_wq9tld.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514704/tmbw/PF/PF_02/PF_02_02_uxaqb4.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514704/tmbw/PF/PF_02/PF_02_03_nlvwuj.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514704/tmbw/PF/PF_02/PF_02_04_wnc65v.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514704/tmbw/PF/PF_02/PF_02_05_tugamn.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514704/tmbw/PF/PF_02/PF_02_06_euimu6.jpg"]
}, {
  "id": "P_03",
  "city": "Pforzheim",
  "type": "Stadtführung",
  "people": ["Familie", "Einzeln"],
  "title": "Mit Alpakas durch Pforzheim",
  "intro": "Mit Alpakas gemütlich Pforzheimer Geschichten und den Enzkreis entdecken.",
  "description": "Sie sind flauschig, gemütlich und man verliebt sich in ihr rundes Gesicht: Alpakas kann man bei Pforzheim nicht nur anschmachten, sondern mit ihnen zusammen auf Wanderung gehen. Es ist ein Erlebnis für die ganze Familie. Auch Gin-, Cocktail- oder Weinwanderungen locken mit regionalen Köstlichkeiten sowie ein flauschiges Alpakaglück.",
  "amenities": "",
  "more": "",
  "link": "https://www.huehnerglueck.de/alpakagl%C3%BCck/",
  "price": "ab 20 €",
  "priceRange": "10-50€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514713/tmbw/PF/PF_03/PF_03_01_okeqc9.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514713/tmbw/PF/PF_03/PF_03_02_wllyit.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514713/tmbw/PF/PF_03/PF_03_03_vllps4.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514713/tmbw/PF/PF_03/PF_03_04_buwvtv.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514712/tmbw/PF/PF_03/PF_03_05_duzvqc.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514713/tmbw/PF/PF_03/PF_03_06_knv4zf.jpg"]
}, {
  "id": "P_04",
  "city": "Pforzheim",
  "type": ["Übernachtung", "Kultur"],
  "people": ["Einzeln", "Zu zweit"],
  "title": "Hohenwart Forum in Pforzheim",
  "intro": "Übernachtungspakete mit vollem Kulturgenuss",
  "description": "Naturnah nächtigen und trotzdem den vollen Kulturgenuss genießen? Das gibt es beim Hohenwart Forum in Pforzheim. Das Hotel im Grünen bietet verschiedene Pakete mit denen man die Museen & Klöster der Umgebung erkunden oder in die Geschichte der Schmuck- und Uhrenindustrie eintauchen kann. Für Westwegabenteurer bietet das Haus ebenfall ein reizvolles Angebot.",
  "amenities": "",
  "more": "",
  "link": "https://www.hohenwart.de/hotel/urlaub/",
  "price": "ab 90 €",
  "priceRange": "50-100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_01_cl6kg1.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_02_vvomvs.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_03_nxyalt.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_04_nkbzls.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_05_bs5irm.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_06_psez6i.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_07_tbqt4q.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_08_ytvnxa.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514723/tmbw/PF/PF_04/PF_04_09_qe0c0u.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1621514722/tmbw/PF/PF_04/PF_04_10_fvdgwf.jpg"]
}, {
  "id": "BB_01",
  "city": "Baden-Baden",
  "type": "Stadtführung",
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "ErlebnisTour Baden-Baden",
  "intro": "Mit dem Segway durch Baden-Baden oder das Rebland",
  "description": "Entdecken Sie mit uns das traumhaft schöne Städtchen Baden-Baden! \nUnsere ca. 2,5-stündige Tour durch die Kurstadt führt uns vorbei an vielen Sehenswürdigkeiten, die man hier kaum alle aufzählen kann. Um nur ein paar hiervon zu nennen: Wir \"schweben\" vorbei am Festspielhaus Baden-Baden, das modernste seiner Art in Deutschland! Weiter auf der Kaiserallee zur Trinkhalle, danach geht es weiter in Richtung Kurhaus. Auch das Theater und die Staatliche Kunsthalle werden wir nicht auslassen!\n\n\n\nAber nicht nur historische Gebäude, sondern auch viel Natur steht auf dem Programm, denn in der traumhaft schönen Lichtentaler Allee heisst es: Natur pur. Harmonisch fügen wir uns hier ein und werden auch einen optionalen Stopp im Kloster Lichtenthal einlegen. Später folgen dann noch Sehenswürdigkeiten wie Augustaplatz und Leopoldsplatz, bis wir an den Bädern und der bekannten Caracalla Therme ankommen.\n\n\n\nAuch das Friedrichsbad liegt nun vor unseren Füßen. 20cm über dem Boden schweben wir weiter und gelangen kurzerhand auf den Marktplatz und zur Stiftskirche, bis es dann langsam wieder in Richtung Kaiserallee geht. Das Festspielhaus wollen wir uns natürlich nicht entgehen lassen. Diese Tour ist eine der schönsten SEGWAY-Touren Deutschlands, dank der wundervollen Stadt und der Natur Baden-Badens, die Sie beinahe „schwebend“ ganz neu erleben werden!",
  "amenities": "",
  "more": "",
  "link": "https://www.city-seg.de/ba-touren-details?tid=2",
  "price": "Preise ab €69.- je Teilnehmer.",
  "priceRange": "50-100€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623744762/tmbw/BB/BB_01/BB_07_cvmuqe.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623744762/tmbw/BB/BB_01/BB_08_rnsbnf.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623744776/tmbw/BB/BB_01/BB_09_qldtt4.jpg"]
}, {
  "id": "B_02",
  "city": "Baden-Baden",
  "type": "Stadtführung",
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Stadtführung durch Baden-Baden",
  "intro": "Stadt- und Kulturgeschichte erleben",
  "description": "Falls Ihnen spontan die Lust auf Stadt- und Kulturgeschichte kommt, können Sie sich gerne einer unserer öffentlichen Stadtführungen anschließen. Mit Ihrer Gästekarte erhalten Sie sogar 50% Rabatt auf den Ticketpreis.",
  "amenities": "",
  "more": "",
  "link": "https://www.baden-baden.com/fuehrungen/oeffentliche-fuehrungen",
  "price": "8,- €",
  "priceRange": "",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623744698/tmbw/BB/BB_02/BB_13_kulcf7.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623744698/tmbw/BB/BB_02/BB_12_fq9dky.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623744697/tmbw/BB/BB_02/BB_11_bmiyt4.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623744697/tmbw/BB/BB_02/BB_10_iodpj6.jpg"]
}, {
  "id": "BB_03",
  "city": "Baden-Baden",
  "type": "Tageserlebnis",
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Wellness in Baden-Baden",
  "intro": "Entspannung in der Caracalla Therme",
  "description": "Auf mehr als 4000 m² bietet die Caracalla Therme viel Platz für wohltuende Entspannung und ausgiebiges Badevergnügen im heißen Thermalwasser. Die Badelandschaft mit ihren abwechslungsreichen Wasserflächen und die römische Saunalandschaft mit Außenbereich im malerischen Schlossgarten laden zum Wohlfühlen ein.",
  "amenities": "",
  "more": "",
  "link": "https://www.shop-carasana.de/vouchers/category/",
  "price": "15 - 27,- €",
  "priceRange": "",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623688353/tmbw/BB/BB_03/BB_02_jk6foq.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623688353/tmbw/BB/BB_03/BB_03_cblqza.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623688353/tmbw/BB/BB_03/BB_01_xhsf4c.jpg"]
}, {
  "id": "BB_04",
  "city": "Baden-Baden",
  "type": "Kultur",
  "people": ["Einzeln", "Zu zweit", "Gruppe", "Familie"],
  "title": "Kultur in Baden-Baden",
  "intro": "Ein Besuch im Museum Frieder Burda",
  "description": "Das Museum Frieder Burda als Lebenswerk\nUm die Sammlung zu bewahren und der Öffentlichkeit zugänglich zu machen, wurde 1998 –nachdem Bemühungen, diese im südfranzösischen Mougins zu etablieren, aufgegeben wurden – die Stiftung Frieder Burda gegründet. Sie legte den Grundstock für den vom amerikanischen Star-Architekten Richard Meier entworfenen Museumsbau, der seit 2004 die Sammlung Frieder Burda in Baden-Baden im Zusammenspiel mit anderen internationalen Meisterwerken präsentiert: Ein strahlend weißer Solitär in der historischen Lichtentaler Allee, heute vielmals als das „Juwel im Park“ bezeichnet.\n\nZahlreiche hochkarätige Ausstellungen wurden seitdem dort gezeigt, u.a. mit Gerhard Richter, Sigmar Polke, Katharina Grosse, William N. Copley, Andreas Gursky und James Turrell. Dazu kamen thematische Ausstellungen wie „Die Bilder tun was mit mir“ oder „America! America!“. Die engagierte und profunde Vermittlung von Kunst mit sozialem Anspruch durch die Kunstwerkstatt des Museums war Frieder Burda, Ehrenbürger der Stadt Baden-Baden, dabei immer eine Herzensangelegenheit. 2014 wurde mit zwei großen Übersichtsausstellungen unter dem Titel „40I10“ das 10jährige Jubiläum im Museum gefeiert. Aus Anlass des 15ten Jubiläums war 2019 aktuell die Ausstellung „Ensemble“ zu sehen, die anhand des Zusammenspiels mit Meisterwerken aus der Sammlung des Centre Pompidou in Paris die deutsch-französische Freundschaft feiert. Anfang 2019 hatte das Haus noch durch eine Banksy-Ausstellung für Furore gesorgt. Mit dem Salon Berlin, den Frieder Burdas Patricia Kamp leitet, schlägt das Museum eine Brücke in die Gegenwartskunst.\n\nImmer hat Frieder Burda sich neuen Anregungen und der Auseinandersetzung mit diesen gestellt. Zugleich blieb er sich stets treu in seinem Glauben an die verbindenden Kräfte der Kunst. Zu der Ausstellung „Ensemble“ hatte er, der leidenschaftliche Frankophile, noch im Katalog geschrieben: „Die Spiegelung der beiden Sammlungen, die Gegenüberstellung einzelner Werke deutscher und französischer Künstler zeigt, wie sehr die Kunst verbindet, sich über Grenzen hinweg positiv beeinflusst und ergänzt. Das macht mich froh und bestärkt mich im Glauben an das universell Verbindende der Kunst, ihre Gültigkeit und ihr Bestehenbleiben über alle Krisen hinweg.“ Am 14. Juli 2019, dem französischen Nationalfeiertag, ist Frieder Burda 83jährig in Baden-Baden im Kreis seiner Familie gestorben.\n\nUngebrochen war sein Glaube an die versöhnliche Macht der Kunst, uneingeschränkt seine Faszination für die mitreißende Kraft der Farben: Mit Frieder Burda hat die Kunstwelt einen seiner großen Sammler, der seine Liebe und Begeisterung für die Kunst immer mit möglichst vielen Menschen teilen wollte, verloren. Humanistische Werte waren ihm stets wichtiger als materielle, der Besitz von Kunst war ihm immer Verpflichtung, diese zugänglich zu machen.\n\nAls Freund der Künstler suchte Frieder Burda den Austausch über die Ursprünge der Kunst, den unmittelbaren und inspirierenden Kontakt mit den Schaffenden. Als Stifter und Museumsgründer beschenkte er seine Heimatstadt großzügig mit einem Haus, das bis heute Menschen aus aller Welt nach Baden-Baden lockt. Als Vorstand seiner Stiftung war er für seine Mitarbeiter immer Vorbild an Bescheidenheit und Menschlichkeit. Und als Privatmensch Seite an Seite mit seiner Frau Elke hat er es vermocht, Familie und Freunde im Zeichen der Kunst immer wieder neu zusammenzuführen.",
  "amenities": "",
  "more": "",
  "link": "https://museum-frieder-burda.ticketfritz.de/Home/Index",
  "price": "14 ,- €",
  "priceRange": "10-50€",
  "pictures": ["https://res.cloudinary.com/viewyork-media/image/upload/v1623744294/tmbw/BB/BB_04/BB_15_ulbd04.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623744294/tmbw/BB/BB_04/BB_05_dxcwzn.jpg", "https://res.cloudinary.com/viewyork-media/image/upload/v1623744293/tmbw/BB/BB_04/BB_14_lcq7sc.jpg"]
}]

export default offers;
